INSERT INTO PARTS (partname, description) VALUES ('TAIL-LIGHT', 'ALERTS DRIVERS IN BACK ON WHEN TO STOP');
INSERT INTO PARTS (partname, description) VALUES ('HEAD-LIGHT', 'SHOWS FRONT WAY');
INSERT INTO PARTS (partname, description) VALUES ('RIGHT-SIDE-INDICATOR', 'SHOWS RIGHT SIDE LIGHT TO TURN');