INSERT INTO PERSON (NAME) VALUES ('TINTIN');
INSERT INTO PERSON (NAME) VALUES ('SNOWY');
INSERT INTO PERSON (NAME) VALUES ('CAPTAIN');
INSERT INTO PERSON (NAME) VALUES ('HADDOCK');
INSERT INTO PERSON (NAME) VALUES ('CALCULUS');
